"""empty message

Revision ID: 0c2b4ab3baf6
Revises: 54b852c2adcb
Create Date: 2021-05-17 02:04:30.694811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2b4ab3baf6'
down_revision = '54b852c2adcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('facebook', sa.String(length=80), nullable=True))
    op.add_column('Users', sa.Column('github', sa.String(length=80), nullable=True))
    op.add_column('Users', sa.Column('instagram', sa.String(length=80), nullable=True))
    op.add_column('Users', sa.Column('linkedin', sa.String(length=80), nullable=True))
    op.add_column('Users', sa.Column('twitter', sa.String(length=80), nullable=True))
    op.add_column('Users', sa.Column('youtube', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'youtube')
    op.drop_column('Users', 'twitter')
    op.drop_column('Users', 'linkedin')
    op.drop_column('Users', 'instagram')
    op.drop_column('Users', 'github')
    op.drop_column('Users', 'facebook')
    # ### end Alembic commands ###
