"""empty message

Revision ID: 2e9b01513e9e
Revises: d44879ef8c83
Create Date: 2021-09-24 17:40:40.074564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9b01513e9e'
down_revision = 'd44879ef8c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'is_active')
    # ### end Alembic commands ###
