"""empty message

Revision ID: 33e03072eaeb
Revises: c83b9b366d5d
Create Date: 2021-05-20 08:30:18.973631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e03072eaeb'
down_revision = 'c83b9b366d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Views', sa.Column('task_id', sa.Integer(), nullable=True))
    op.add_column('Views', sa.Column('week_num', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Views', 'Tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Views', type_='foreignkey')
    op.drop_column('Views', 'week_num')
    op.drop_column('Views', 'task_id')
    # ### end Alembic commands ###
