"""empty message

Revision ID: 43bf4fa7255a
Revises: 2e9b01513e9e
Create Date: 2021-10-07 11:38:04.993309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43bf4fa7255a'
down_revision = '2e9b01513e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Categories', sa.Column('cat_pic', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Categories', 'cat_pic')
    # ### end Alembic commands ###
