"""empty message

Revision ID: 54b852c2adcb
Revises: 
Create Date: 2021-05-15 08:05:04.163915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b852c2adcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('task_pic', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'task_pic')
    # ### end Alembic commands ###
