"""empty message

Revision ID: 80232608d799
Revises: 
Create Date: 2021-10-26 21:55:04.295396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80232608d799'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SiteSettings', 'mail_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('SiteSettings', 'mail_server',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('SiteSettings', 'password',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('SiteSettings', 'port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('SiteSettings', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SiteSettings', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('SiteSettings', 'port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('SiteSettings', 'password',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('SiteSettings', 'mail_server',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('SiteSettings', 'mail_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
