"""empty message

Revision ID: 8f850b6d8cc0
Revises: 
Create Date: 2021-05-24 11:41:03.432279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f850b6d8cc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Offers', sa.Column('offered_task', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Offers', 'Tasks', ['offered_task'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Offers', type_='foreignkey')
    op.drop_column('Offers', 'offered_task')
    # ### end Alembic commands ###
