"""empty message

Revision ID: c83b9b366d5d
Revises: 0c2b4ab3baf6
Create Date: 2021-05-17 04:16:44.774499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83b9b366d5d'
down_revision = '0c2b4ab3baf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reviews', sa.Column('freelancer', sa.Integer(), nullable=True))
    op.drop_constraint('Reviews_professional_fkey', 'Reviews', type_='foreignkey')
    op.create_foreign_key(None, 'Reviews', 'Users', ['freelancer'], ['id'])
    op.drop_column('Reviews', 'professional')
    op.add_column('Users', sa.Column('country', sa.String(length=25), nullable=True))
    op.drop_column('Users', 'province')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('province', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.drop_column('Users', 'country')
    op.add_column('Reviews', sa.Column('professional', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Reviews', type_='foreignkey')
    op.create_foreign_key('Reviews_professional_fkey', 'Reviews', 'Users', ['professional'], ['id'])
    op.drop_column('Reviews', 'freelancer')
    # ### end Alembic commands ###
