"""empty message

Revision ID: d44879ef8c83
Revises: 8f850b6d8cc0
Create Date: 2021-09-16 16:12:51.871852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44879ef8c83'
down_revision = '8f850b6d8cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('username', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'username')
    # ### end Alembic commands ###
